var texts = [
  'tudo que dá brilho ao nosso mundo.',
  'tudo que expressa a vontade do ser-humano.',
  'tudo que nos dispersa um sentimento.',
  'tudo que transforma o comum em extraordinário.',
  'tudo que provoca reflexão no observador.',
  'tudo que traduz emoções em formas e cores.',
  'tudo que conecta pessoas através de sentimentos.',
  'tudo que nos permite sonhar acordados.',
  'tudo que quebra barreiras da realidade.',
  'tudo que desafia a lógica e a razão.',
  'tudo que eterniza momentos efêmeros.',
  'tudo que dá voz ao invisível.',
  'tudo que emociona sem palavras.',
  'tudo que revela a beleza oculta.',
  'tudo que questiona padrões estabelecidos.',
  'tudo que transforma ideias em experiências.',
  'tudo que desperta sentidos adormecidos.',
  'tudo que expressa o que palavras não alcançam.',
  'tudo que aproxima o humano do divino.',
  'tudo que celebra a diversidade de perspectivas.',
  'tudo que nos faz olhar para dentro.',
  'tudo que cria pontes entre culturas.',
  'tudo que desafia o tempo e o espaço.',
  'tudo que transforma dor em expressão.',
  'tudo que nos faz sentir vivos.',
  'tudo que revela o mundo de maneira nova.',
  'tudo que nos inspira a criar.',
  'tudo que mistura razão e emoção.',
  'tudo que transforma simples gestos em poesia.',
  'tudo que reflete a alma de quem cria.',
  'tudo que nos conecta ao coletivo.',
  'tudo que provoca questionamentos profundos.',
  'tudo que traduz sentimentos universais.',
  'tudo que transforma a rotina em experiência.',
  'tudo que desafia expectativas.',
  'tudo que mostra a beleza nas imperfeições.',
  'tudo que transforma memória em história.',
  'tudo que captura a essência do instante.',
  'tudo que nos faz perceber detalhes invisíveis.',
  'tudo que mistura sonho e realidade.',
  'tudo que emociona sem tocar fisicamente.',
  'tudo que nos transporta para outros mundos.',
  'tudo que brinca com cores e formas.',
  'tudo que transforma pensamento em imagem.',
  'tudo que nos conecta com o passado.',
  'tudo que cria novas possibilidades.',
  'tudo que desafia convenções.',
  'tudo que nos faz sentir empatia.',
  'tudo que transforma silêncio em expressão.',
  'tudo que revela a complexidade da vida.',
  'tudo que provoca sensações inesperadas.',
  'tudo que dá forma ao invisível.',
  'tudo que une razão e intuição.',
  'tudo que captura a essência da existência.',
  'tudo que transforma ideias em realidade.',
  'tudo que revela mundos desconhecidos.',
  'tudo que provoca reflexão sobre si mesmo.',
  'tudo que mistura passado e futuro.',
  'tudo que transforma experiência em significado.',
  'tudo que conecta pensamentos e emoções.',
  'tudo que transcende fronteiras físicas.',
  'tudo que transforma o ordinário em extraordinário.',
  'tudo que provoca encantamento.',
  'tudo que revela novas perspectivas.',
  'tudo que transforma silêncio em música.',
  'tudo que cria mundos imaginários.',
  'tudo que traduz sentimentos profundos.',
  'tudo que desafia o olhar comum.',
  'tudo que transforma o cotidiano em arte.',
  'tudo que revela a essência da humanidade.',
  'tudo que desperta curiosidade.',
  'tudo que provoca introspecção.',
  'tudo que mistura ciência e emoção.',
  'tudo que transforma lembranças em imagens.',
  'tudo que nos faz perceber a beleza ao redor.',
  'tudo que dá vida ao que era estático.',
  'tudo que transforma gestos simples em expressão.',
  'tudo que cria experiências sensoriais.',
  'tudo que conecta passado, presente e futuro.',
  'tudo que mistura tradição e inovação.',
  'tudo que transforma ideias em experiências sensíveis.',
  'tudo que revela a força da imaginação.',
  'tudo que provoca emoções inesperadas.',
  'tudo que transforma o ordinário em extraordinário.',
  'tudo que nos faz refletir sobre a existência.',
  'tudo que mistura técnica e emoção.',
  'tudo que dá significado ao que parece sem sentido.',
  'tudo que conecta cultura e sentimento.',
  'tudo que transforma pensamentos em ação.',
  'tudo que revela a poesia do cotidiano.',
  'tudo que provoca encantamento visual.',
  'tudo que transforma lembranças em arte.',
  'tudo que mistura percepção e emoção.',
  'tudo que nos faz ver o mundo de forma diferente.',
  'tudo que transforma ideias em sensações.',
  'tudo que revela a complexidade da mente humana.',
  'tudo que provoca introspecção profunda.',
  'tudo que mistura criação e observação.',
  'tudo que transforma sentimentos em linguagem.',
  'tudo que conecta o interno ao externo.',
  'tudo que dá vida à imaginação.',
  'tudo que provoca conexão entre pessoas.',
  'tudo que transforma experiências em memórias.',
  'tudo que revela a diversidade do mundo.',
  'tudo que mistura realidade e fantasia.',
  'tudo que nos faz questionar a normalidade.',
  'tudo que transforma a percepção em emoção.',
  'tudo que cria beleza no inesperado.',
  'tudo que revela a profundidade do espírito human'
];


const styles = [
    "italic",
    "bolder",
    "bold",
    "normal"
]

setInterval(()=>{
    let randomText = texts[Math.floor(Math.random() * texts.length)];
    let randomStyle = styles[Math.floor(Math.random() * texts.length)];

    document.getElementById("hoverarttext").innerHTML =
        '"A arte é<span id="hoverarttextspan">'+randomText+'</span>"'

    document.getElementById("hoverarttextspan").style.fontStyle = randomStyle;
},3000)